### ISSUE TITLE
Make work for Tensorflow 1.6.0

### ISSUE THREAD

**Issue by jtlz2** [BartyzalRadek/Multi-label-Inception-net#11]
Lots of crashing errors here, mostly relating to the summary module

When running retrain.py,

`AttributeError: 'module' object has no attribute 'scalar_summary'`

See [here](https://stackoverflow.com/questions/41066244/tensorflow-module-object-has-no-attribute-scalar-summary) for trivial solution

Similarly `histogram_summary`

AttributeError: 'module' object has no attribute 'mul'

AttributeError: 'module' object has no attribute 'pack'

**Comment by haoxi911** [comment]
Not sure if we are able to adapt it to TensorFlow 1.8. 

Note: in 1.8, TensorFlow starts to use a separate repository for reusable models or retrain scripts, it is called `TensorFlow Hub`.

**Comment by eyaler** [comment]
https://github.com/BartyzalRadek/Multi-label-Inception-net/pull/14

**Comment by BartyzalRadek** [comment]
Merged. Thanks eyaler.

**Comment by haoxi911** [comment]
Thanks @eyaler !
