### ISSUE TITLE
Low recall and wrong classification result

### ISSUE THREAD

**Issue by tianyuecao** [BartyzalRadek/Multi-label-Inception-net#17]
Hi, @BartyzalRadek, thank you for sharing the code. But I found that when i use the code train on MS-COCO 2014, it can only predict label 'person' but no other labels. And this results in low recall. Do you have any suggestions, please? Thanks!

**Comment by sunjinr** [comment]
hi there, did you find a better algorithm for multi-label image classification?

**Comment by tianyuecao** [comment]
> hi there, did you find a better algorithm for multi-label image classification?

actually there are some papers about multi-label image classification with codes, such as https://github.com/HCPLab-SYSU/SSGRL etc.
