### ISSUE TITLE
Is it possible to get detection_boxes:0 tensor?

### ISSUE THREAD

**Issue by xMonty** [BartyzalRadek/Multi-label-Inception-net#19]
Hi,
i would like to get the detection boxes as well if thats possible,
i tried calling detection_boxes = sess.graph.get_tensor_by_name('detection_boxes:0') but it said that tensor doesn't exist.
any help would be appreciated 
Thanks

**Comment by BartyzalRadek** [comment]
This network does not predict detection boxes. 
It is doing **multi-label** classification not **multi-class**. 
See: https://scikit-learn.org/stable/modules/multiclass.html
